apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
spec:
  ingressDomain: localhost
  deploymentPlan:
    size: 2
    persistenceEnabled: true
    initImage: localhost:32000/siav-artemis-init-grouping-handler:1.0
    extraMounts:
      configMaps:
      - "artemis-logging-config"
  console:
    expose: true
  addressSettings:
    applyRule: merge_all
    addressSetting:
    - match: '#'
      defaultGroupRebalance: true
      defaultGroupBuckets: 5
      defaultGroupRebalancePauseDispatch: true
      redistributionDelay: 0