apiVersion: v1
kind: Service
metadata:
  name: activemq-artemis-ext-acceptor-0-svc
  labels:
    app: activemq-artemis
  annotations:
    metallb.universe.tf/allow-shared-ip: "share-ip"  
spec:
  selector:
    ActiveMQArtemis: artemis-broker
    application: artemis-broker-app
    "statefulset.kubernetes.io/pod-name": artemis-broker-ss-0
  ports:
    - name: tcp
      protocol: TCP
      port: 61616
      targetPort: 61616
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: activemq-artemis-ext-acceptor-1-svc
  labels:
    app: activemq-artemis
  annotations:
    metallb.universe.tf/allow-shared-ip: "share-ip"
spec:
  selector:
    ActiveMQArtemis: artemis-broker
    application: artemis-broker-app
    "statefulset.kubernetes.io/pod-name": artemis-broker-ss-1
  ports:
    - name: tcp
      protocol: TCP
      port: 61626
      targetPort: 61616
  type: LoadBalancer
